[package]
name = "axum-live-coding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
axum = "0.5.4"
tokio = { version = "1.18.2", features = ["full"] }
